### ISSUE TITLE
Push to @cycle npm namespace

### ISSUE THREAD

**Issue by secobarbital** [cyclejs/cycle-fetch-driver#1]
@staltz I finally cleaned up everything and added tests for this driver but when I tried, I don't have permission to transfer ownership to the cyclejs org and push to the @cycle namespace. I assume you'll have to grant those.

**Comment by staltz** [comment]
In Github, you should be able to transfer ownership now. In `npm`, unfortunately they still don't support proper "organizations" like Github (scoped namespaces are primarily meant for a single user), so I would have to do the publishing whenever needed.

**Comment by secobarbital** [comment]
Got it. Thanks!

**Comment by secobarbital** [comment]
@staltz Do you mind publishing this to npm? Thanks!

Let me know if it becomes a hassle and I should split it out of the namespace.

**Comment by staltz** [comment]
Done!

**Comment by secobarbital** [comment]
:ok_hand:
