### ISSUE TITLE
Package is missing the lib directory in npm

### ISSUE THREAD

**Issue by secobarbital** [cyclejs/cycle-fetch-driver#3]
The `lib/.gitignore` ignores all transpiled files in `lib` and without a matching `.npmignore` file npm ignores this directory as well. Need to unignore this directory.

**Comment by secobarbital** [comment]
@staltz Please publish v1.0.1. Thanks!

**Comment by secobarbital** [comment]
Now v2.0.0 after updating peer deps to `@cycle/core` v4

**Comment by staltz** [comment]
Done
